# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://niallburkley.com
enforce_ssl: niallburkley.com

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Niall Burkley's Developer Blog
  avatar: profile-small.jpg
  gravatar: # Email MD5 hash
  description: "Web Developer Blog covering ruby and other web technologies"

  # Header and footer text
  header_text: >
    <p>
      Software Developer based in Boston, USA, working with
      <a href="https://www.meltwater.com/?ucs">Meltwater</a>, formerly <a href="https://www.edenspiekermann.com/">Edenspiekermann</a>.
    </p>

    <p>I can usually be found writing <code>ruby</code>, <code>elixir</code> and <code>JavaScript</code> for the web.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  facebook:
  flickr:
  github: "nburkley"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  tumblr:
  twitter: "niallburkley"
  youtube:

  # Scripts
  google_analytics: UA-64443693-1
  disqus_shortname: niallburkley

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

permalink: /blog/:title/

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"
# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-sitemap
